### ISSUE TITLE
initFromSPI sets incorrect SE mode

### ISSUE THREAD

**Issue by smillidge** [WASdev/standards.jsr352.jbatch#26]
The code below sets SE mode to true in the service properties if eeMode is true rather than if it is false.	

private void initFromSPI() {
//Merge in overrides from the SPI so the container can change properties
batchContainerProps.putAll(BatchSPIManager.getInstance().getBatchContainerOverrideProperties());
Boolean eeMode = BatchSPIManager.getInstance().getEEMode();
if (eeMode != null) {
String boolVal = eeMode.toString();
logger.config("Override platform selection (EE=true, SE=false) with value from SPI: " + boolVal);
batchContainerProps.setProperty(ServiceTypes.J2SE_MODE, boolVal);
}
}

**Comment by scottkurz** [comment]
Whoops.  Thanks for catching that...

I also exposed the "platform mode" from ServicesManager so I could add a couple tests here.
