### ISSUE TITLE
Mvn generate of TCK batch.xml has issues in Cygwin

### ISSUE THREAD

**Issue by scottkurz** [WASdev/standards.jsr352.jbatch#32]
The Separator of '\\' and the POM arg "com/ibm/jbatch/tck/artifacts/" aren't combining well.    

Appreciate the idea here so rather than back the Java logic of @BrentDouglas  I'll just checkin batch.xml as a source and comment it out of the build for now.

**Comment by BrentDouglas** [comment]
Sorry, I don't use windows so never really think about it. You should be able to work around it by adding this to the <properties> section (for brevity):
```xml
<fs>${file.separator}</fs>
```
And then replacing the '/'s inthe args with ${fs}. Something like

```xml
<echo message="building ${project.basedir}${fs}src${fs}main${fs}resources${fs}META-INF${fs}build.xml"/>
<java classname="com.ibm.jbatch.tck.utils.BatchXMLGenerator">
    <arg value="${project.build.outputDirectory}"/>
    <arg value="com${fs}ibm${fs}jbatch${fs}tck${fs}artifacts${fs}"/>
    <arg value="${project.basedir}${fs}src${fs}main${fs}resources${fs}META-INF"/>
    <classpath refid="maven.compile.classpath"/>
    <classpath>
        <dirset dir="${project.build.outputDirectory}/com/ibm/jbatch/tck">
            <include name="artifacts utils"/>
        </dirset>
    </classpath>
</java>
```

**Comment by BrentDouglas** [comment]
Also, if you are changing it, I mistakenly wrote build.xml rather than batch.xml in that log message.

**Comment by scottkurz** [comment]
Thanks for the tips.
