### ISSUE TITLE
Update "about" section on main github page

### ISSUE THREAD

**Issue by kwsutter** [WASdev/standards.jsr352.jbatch#71]
Hi,
I received a comment from Ed Bratt that the "About" section on the github home page for this repository says "reference implementation".  We should change this to "compatible implementation".  For reference, here's the text I am referring to...

```
About

Home of 'jbatch', the Reference Implementation for the Java Batch standard (JSR 352, Batch Applications for the Java Platform). #JavaEE7 
```

The README is quite clear on the old reference impl vs compatible impl, but this About section could be improved.  Thanks!

**Comment by scottkurz** [comment]
I changed to:
> Home of 'jbatch', a compatible implementation of the Jakarta Batch specification (and the former Reference Implementation for the JSR 352, Batch Applications for the Java Platform specification). 

Please reopen if you have any comments on that. Thanks.
